#!/bin/bash
rm build_log.txt >>build_log.txt
echo Cleaning workspace ...
rm -rf *.zip
cd flashable/zip/kernel/
rm -rf zImage
cd ../../..
cd flashable/zip/system/lib/modules/
rm -rf bcmdhd.ko
cd ../../..
make clean | tee build_log.txt
echo >> build_log.txt
echo Writing configs ...
make doubleshot_defconfig | tee -a build_log.txt
echo >> build_log.txt
make -j3 | tee -a build_log.txt
echo Copying files and making flashable
cp -f arch/arm/boot/zImage flashable/zip/kernel/zImage
cp -f drivers/net/wireless/bcmdhd/bcmdhd.ko flashable/zip/system/lib/modules/bcmdhd.ko
cd flashable/zip/
zip -r9 ../../WildKernel.zip *
cd ../..
java -jar flashable/tools/signapk.jar flashable/tools/testkey.x509.pem flashable/tools/testkey.pk8 WildKernel.zip WildKernel_signed.zip
rm -rf WildKernel.zip
echo done
